package model;

public class Coalfieldzonebean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.COALFIELDZONEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String coalfieldzoneid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.ZONECODE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String zonecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.ZONENAME
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String zonename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.STARTLOCATION
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String startlocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.ENDLOCATION
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String endlocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.LEDDEVICEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String leddeviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.STOPDEVICEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String stopdeviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.COALFIELDID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String coalfieldid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.STOPTYPE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String stoptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.QUALITYTYPE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String qualitytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.STARTLOCATIONX
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String startlocationx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.ENDLOCATIONX
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String endlocationx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.STARTLOCATIONY
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String startlocationy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.ENDLOCATIONY
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String endlocationy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.ZONETYPE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String zonetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.BLENDINGFLAG
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String blendingflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.STARTANGLE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String startangle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.ENDANGLE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String endangle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.INRFIDDEVICEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String inrfiddeviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.OUTRFIDDEVICEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String outrfiddeviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.VOICEDEVICEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String voicedeviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.QNETARUPPERLIMIT
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String qnetarupperlimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.QNETARLOWERLIMIT
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String qnetarlowerlimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.STDUPPERLIMIT
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String stdupperlimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.STDLOWERLIMIT
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String stdlowerlimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.COALFIELDZONEGUID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String coalfieldzoneguid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.COALFIELDZONEID
     *
     * @return the value of COALFIELDZONE.COALFIELDZONEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getCoalfieldzoneid() {
        return coalfieldzoneid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.COALFIELDZONEID
     *
     * @param coalfieldzoneid the value for COALFIELDZONE.COALFIELDZONEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setCoalfieldzoneid(String coalfieldzoneid) {
        this.coalfieldzoneid = coalfieldzoneid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.ZONECODE
     *
     * @return the value of COALFIELDZONE.ZONECODE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getZonecode() {
        return zonecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.ZONECODE
     *
     * @param zonecode the value for COALFIELDZONE.ZONECODE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setZonecode(String zonecode) {
        this.zonecode = zonecode == null ? null : zonecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.ZONENAME
     *
     * @return the value of COALFIELDZONE.ZONENAME
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getZonename() {
        return zonename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.ZONENAME
     *
     * @param zonename the value for COALFIELDZONE.ZONENAME
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setZonename(String zonename) {
        this.zonename = zonename == null ? null : zonename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.STARTLOCATION
     *
     * @return the value of COALFIELDZONE.STARTLOCATION
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getStartlocation() {
        return startlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.STARTLOCATION
     *
     * @param startlocation the value for COALFIELDZONE.STARTLOCATION
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setStartlocation(String startlocation) {
        this.startlocation = startlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.ENDLOCATION
     *
     * @return the value of COALFIELDZONE.ENDLOCATION
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getEndlocation() {
        return endlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.ENDLOCATION
     *
     * @param endlocation the value for COALFIELDZONE.ENDLOCATION
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setEndlocation(String endlocation) {
        this.endlocation = endlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.LEDDEVICEID
     *
     * @return the value of COALFIELDZONE.LEDDEVICEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getLeddeviceid() {
        return leddeviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.LEDDEVICEID
     *
     * @param leddeviceid the value for COALFIELDZONE.LEDDEVICEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setLeddeviceid(String leddeviceid) {
        this.leddeviceid = leddeviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.STOPDEVICEID
     *
     * @return the value of COALFIELDZONE.STOPDEVICEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getStopdeviceid() {
        return stopdeviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.STOPDEVICEID
     *
     * @param stopdeviceid the value for COALFIELDZONE.STOPDEVICEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setStopdeviceid(String stopdeviceid) {
        this.stopdeviceid = stopdeviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.COALFIELDID
     *
     * @return the value of COALFIELDZONE.COALFIELDID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getCoalfieldid() {
        return coalfieldid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.COALFIELDID
     *
     * @param coalfieldid the value for COALFIELDZONE.COALFIELDID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setCoalfieldid(String coalfieldid) {
        this.coalfieldid = coalfieldid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.STOPTYPE
     *
     * @return the value of COALFIELDZONE.STOPTYPE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getStoptype() {
        return stoptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.STOPTYPE
     *
     * @param stoptype the value for COALFIELDZONE.STOPTYPE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setStoptype(String stoptype) {
        this.stoptype = stoptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.QUALITYTYPE
     *
     * @return the value of COALFIELDZONE.QUALITYTYPE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getQualitytype() {
        return qualitytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.QUALITYTYPE
     *
     * @param qualitytype the value for COALFIELDZONE.QUALITYTYPE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setQualitytype(String qualitytype) {
        this.qualitytype = qualitytype == null ? null : qualitytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.STARTLOCATIONX
     *
     * @return the value of COALFIELDZONE.STARTLOCATIONX
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getStartlocationx() {
        return startlocationx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.STARTLOCATIONX
     *
     * @param startlocationx the value for COALFIELDZONE.STARTLOCATIONX
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setStartlocationx(String startlocationx) {
        this.startlocationx = startlocationx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.ENDLOCATIONX
     *
     * @return the value of COALFIELDZONE.ENDLOCATIONX
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getEndlocationx() {
        return endlocationx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.ENDLOCATIONX
     *
     * @param endlocationx the value for COALFIELDZONE.ENDLOCATIONX
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setEndlocationx(String endlocationx) {
        this.endlocationx = endlocationx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.STARTLOCATIONY
     *
     * @return the value of COALFIELDZONE.STARTLOCATIONY
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getStartlocationy() {
        return startlocationy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.STARTLOCATIONY
     *
     * @param startlocationy the value for COALFIELDZONE.STARTLOCATIONY
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setStartlocationy(String startlocationy) {
        this.startlocationy = startlocationy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.ENDLOCATIONY
     *
     * @return the value of COALFIELDZONE.ENDLOCATIONY
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getEndlocationy() {
        return endlocationy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.ENDLOCATIONY
     *
     * @param endlocationy the value for COALFIELDZONE.ENDLOCATIONY
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setEndlocationy(String endlocationy) {
        this.endlocationy = endlocationy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.ZONETYPE
     *
     * @return the value of COALFIELDZONE.ZONETYPE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getZonetype() {
        return zonetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.ZONETYPE
     *
     * @param zonetype the value for COALFIELDZONE.ZONETYPE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setZonetype(String zonetype) {
        this.zonetype = zonetype == null ? null : zonetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.BLENDINGFLAG
     *
     * @return the value of COALFIELDZONE.BLENDINGFLAG
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getBlendingflag() {
        return blendingflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.BLENDINGFLAG
     *
     * @param blendingflag the value for COALFIELDZONE.BLENDINGFLAG
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setBlendingflag(String blendingflag) {
        this.blendingflag = blendingflag == null ? null : blendingflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.STARTANGLE
     *
     * @return the value of COALFIELDZONE.STARTANGLE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getStartangle() {
        return startangle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.STARTANGLE
     *
     * @param startangle the value for COALFIELDZONE.STARTANGLE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setStartangle(String startangle) {
        this.startangle = startangle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.ENDANGLE
     *
     * @return the value of COALFIELDZONE.ENDANGLE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getEndangle() {
        return endangle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.ENDANGLE
     *
     * @param endangle the value for COALFIELDZONE.ENDANGLE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setEndangle(String endangle) {
        this.endangle = endangle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.INRFIDDEVICEID
     *
     * @return the value of COALFIELDZONE.INRFIDDEVICEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getInrfiddeviceid() {
        return inrfiddeviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.INRFIDDEVICEID
     *
     * @param inrfiddeviceid the value for COALFIELDZONE.INRFIDDEVICEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setInrfiddeviceid(String inrfiddeviceid) {
        this.inrfiddeviceid = inrfiddeviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.OUTRFIDDEVICEID
     *
     * @return the value of COALFIELDZONE.OUTRFIDDEVICEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getOutrfiddeviceid() {
        return outrfiddeviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.OUTRFIDDEVICEID
     *
     * @param outrfiddeviceid the value for COALFIELDZONE.OUTRFIDDEVICEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setOutrfiddeviceid(String outrfiddeviceid) {
        this.outrfiddeviceid = outrfiddeviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.VOICEDEVICEID
     *
     * @return the value of COALFIELDZONE.VOICEDEVICEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getVoicedeviceid() {
        return voicedeviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.VOICEDEVICEID
     *
     * @param voicedeviceid the value for COALFIELDZONE.VOICEDEVICEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setVoicedeviceid(String voicedeviceid) {
        this.voicedeviceid = voicedeviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.QNETARUPPERLIMIT
     *
     * @return the value of COALFIELDZONE.QNETARUPPERLIMIT
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getQnetarupperlimit() {
        return qnetarupperlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.QNETARUPPERLIMIT
     *
     * @param qnetarupperlimit the value for COALFIELDZONE.QNETARUPPERLIMIT
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setQnetarupperlimit(String qnetarupperlimit) {
        this.qnetarupperlimit = qnetarupperlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.QNETARLOWERLIMIT
     *
     * @return the value of COALFIELDZONE.QNETARLOWERLIMIT
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getQnetarlowerlimit() {
        return qnetarlowerlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.QNETARLOWERLIMIT
     *
     * @param qnetarlowerlimit the value for COALFIELDZONE.QNETARLOWERLIMIT
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setQnetarlowerlimit(String qnetarlowerlimit) {
        this.qnetarlowerlimit = qnetarlowerlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.STDUPPERLIMIT
     *
     * @return the value of COALFIELDZONE.STDUPPERLIMIT
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getStdupperlimit() {
        return stdupperlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.STDUPPERLIMIT
     *
     * @param stdupperlimit the value for COALFIELDZONE.STDUPPERLIMIT
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setStdupperlimit(String stdupperlimit) {
        this.stdupperlimit = stdupperlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.STDLOWERLIMIT
     *
     * @return the value of COALFIELDZONE.STDLOWERLIMIT
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getStdlowerlimit() {
        return stdlowerlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.STDLOWERLIMIT
     *
     * @param stdlowerlimit the value for COALFIELDZONE.STDLOWERLIMIT
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setStdlowerlimit(String stdlowerlimit) {
        this.stdlowerlimit = stdlowerlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.COALFIELDZONEGUID
     *
     * @return the value of COALFIELDZONE.COALFIELDZONEGUID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getCoalfieldzoneguid() {
        return coalfieldzoneguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.COALFIELDZONEGUID
     *
     * @param coalfieldzoneguid the value for COALFIELDZONE.COALFIELDZONEGUID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setCoalfieldzoneguid(String coalfieldzoneguid) {
        this.coalfieldzoneguid = coalfieldzoneguid == null ? null : coalfieldzoneguid.trim();
    }
}