package model;

import java.math.BigDecimal;

public class Coalfieldzonebean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.COALFIELDZONEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private BigDecimal coalfieldzoneid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.ZONECODE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String zonecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.ZONENAME
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String zonename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.STARTLOCATION
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private BigDecimal startlocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.ENDLOCATION
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private BigDecimal endlocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.LEDDEVICEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private BigDecimal leddeviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.STOPDEVICEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private BigDecimal stopdeviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.COALFIELDID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private BigDecimal coalfieldid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.STOPTYPE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private Object stoptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.QUALITYTYPE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String qualitytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.STARTLOCATIONX
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private BigDecimal startlocationx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.ENDLOCATIONX
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private BigDecimal endlocationx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.STARTLOCATIONY
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private BigDecimal startlocationy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.ENDLOCATIONY
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private BigDecimal endlocationy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.ZONETYPE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String zonetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.BLENDINGFLAG
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String blendingflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.STARTANGLE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private BigDecimal startangle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.ENDANGLE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private BigDecimal endangle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.INRFIDDEVICEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private BigDecimal inrfiddeviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.OUTRFIDDEVICEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private BigDecimal outrfiddeviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.VOICEDEVICEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private BigDecimal voicedeviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.QNETARUPPERLIMIT
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private BigDecimal qnetarupperlimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.QNETARLOWERLIMIT
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private BigDecimal qnetarlowerlimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.STDUPPERLIMIT
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private BigDecimal stdupperlimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.STDLOWERLIMIT
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private BigDecimal stdlowerlimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELDZONE.COALFIELDZONEGUID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String coalfieldzoneguid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.COALFIELDZONEID
     *
     * @return the value of COALFIELDZONE.COALFIELDZONEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public BigDecimal getCoalfieldzoneid() {
        return coalfieldzoneid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.COALFIELDZONEID
     *
     * @param coalfieldzoneid the value for COALFIELDZONE.COALFIELDZONEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setCoalfieldzoneid(BigDecimal coalfieldzoneid) {
        this.coalfieldzoneid = coalfieldzoneid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.ZONECODE
     *
     * @return the value of COALFIELDZONE.ZONECODE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getZonecode() {
        return zonecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.ZONECODE
     *
     * @param zonecode the value for COALFIELDZONE.ZONECODE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setZonecode(String zonecode) {
        this.zonecode = zonecode == null ? null : zonecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.ZONENAME
     *
     * @return the value of COALFIELDZONE.ZONENAME
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getZonename() {
        return zonename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.ZONENAME
     *
     * @param zonename the value for COALFIELDZONE.ZONENAME
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setZonename(String zonename) {
        this.zonename = zonename == null ? null : zonename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.STARTLOCATION
     *
     * @return the value of COALFIELDZONE.STARTLOCATION
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public BigDecimal getStartlocation() {
        return startlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.STARTLOCATION
     *
     * @param startlocation the value for COALFIELDZONE.STARTLOCATION
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setStartlocation(BigDecimal startlocation) {
        this.startlocation = startlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.ENDLOCATION
     *
     * @return the value of COALFIELDZONE.ENDLOCATION
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public BigDecimal getEndlocation() {
        return endlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.ENDLOCATION
     *
     * @param endlocation the value for COALFIELDZONE.ENDLOCATION
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setEndlocation(BigDecimal endlocation) {
        this.endlocation = endlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.LEDDEVICEID
     *
     * @return the value of COALFIELDZONE.LEDDEVICEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public BigDecimal getLeddeviceid() {
        return leddeviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.LEDDEVICEID
     *
     * @param leddeviceid the value for COALFIELDZONE.LEDDEVICEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setLeddeviceid(BigDecimal leddeviceid) {
        this.leddeviceid = leddeviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.STOPDEVICEID
     *
     * @return the value of COALFIELDZONE.STOPDEVICEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public BigDecimal getStopdeviceid() {
        return stopdeviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.STOPDEVICEID
     *
     * @param stopdeviceid the value for COALFIELDZONE.STOPDEVICEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setStopdeviceid(BigDecimal stopdeviceid) {
        this.stopdeviceid = stopdeviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.COALFIELDID
     *
     * @return the value of COALFIELDZONE.COALFIELDID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public BigDecimal getCoalfieldid() {
        return coalfieldid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.COALFIELDID
     *
     * @param coalfieldid the value for COALFIELDZONE.COALFIELDID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setCoalfieldid(BigDecimal coalfieldid) {
        this.coalfieldid = coalfieldid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.STOPTYPE
     *
     * @return the value of COALFIELDZONE.STOPTYPE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public Object getStoptype() {
        return stoptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.STOPTYPE
     *
     * @param stoptype the value for COALFIELDZONE.STOPTYPE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setStoptype(Object stoptype) {
        this.stoptype = stoptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.QUALITYTYPE
     *
     * @return the value of COALFIELDZONE.QUALITYTYPE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getQualitytype() {
        return qualitytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.QUALITYTYPE
     *
     * @param qualitytype the value for COALFIELDZONE.QUALITYTYPE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setQualitytype(String qualitytype) {
        this.qualitytype = qualitytype == null ? null : qualitytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.STARTLOCATIONX
     *
     * @return the value of COALFIELDZONE.STARTLOCATIONX
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public BigDecimal getStartlocationx() {
        return startlocationx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.STARTLOCATIONX
     *
     * @param startlocationx the value for COALFIELDZONE.STARTLOCATIONX
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setStartlocationx(BigDecimal startlocationx) {
        this.startlocationx = startlocationx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.ENDLOCATIONX
     *
     * @return the value of COALFIELDZONE.ENDLOCATIONX
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public BigDecimal getEndlocationx() {
        return endlocationx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.ENDLOCATIONX
     *
     * @param endlocationx the value for COALFIELDZONE.ENDLOCATIONX
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setEndlocationx(BigDecimal endlocationx) {
        this.endlocationx = endlocationx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.STARTLOCATIONY
     *
     * @return the value of COALFIELDZONE.STARTLOCATIONY
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public BigDecimal getStartlocationy() {
        return startlocationy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.STARTLOCATIONY
     *
     * @param startlocationy the value for COALFIELDZONE.STARTLOCATIONY
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setStartlocationy(BigDecimal startlocationy) {
        this.startlocationy = startlocationy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.ENDLOCATIONY
     *
     * @return the value of COALFIELDZONE.ENDLOCATIONY
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public BigDecimal getEndlocationy() {
        return endlocationy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.ENDLOCATIONY
     *
     * @param endlocationy the value for COALFIELDZONE.ENDLOCATIONY
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setEndlocationy(BigDecimal endlocationy) {
        this.endlocationy = endlocationy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.ZONETYPE
     *
     * @return the value of COALFIELDZONE.ZONETYPE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getZonetype() {
        return zonetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.ZONETYPE
     *
     * @param zonetype the value for COALFIELDZONE.ZONETYPE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setZonetype(String zonetype) {
        this.zonetype = zonetype == null ? null : zonetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.BLENDINGFLAG
     *
     * @return the value of COALFIELDZONE.BLENDINGFLAG
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getBlendingflag() {
        return blendingflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.BLENDINGFLAG
     *
     * @param blendingflag the value for COALFIELDZONE.BLENDINGFLAG
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setBlendingflag(String blendingflag) {
        this.blendingflag = blendingflag == null ? null : blendingflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.STARTANGLE
     *
     * @return the value of COALFIELDZONE.STARTANGLE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public BigDecimal getStartangle() {
        return startangle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.STARTANGLE
     *
     * @param startangle the value for COALFIELDZONE.STARTANGLE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setStartangle(BigDecimal startangle) {
        this.startangle = startangle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.ENDANGLE
     *
     * @return the value of COALFIELDZONE.ENDANGLE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public BigDecimal getEndangle() {
        return endangle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.ENDANGLE
     *
     * @param endangle the value for COALFIELDZONE.ENDANGLE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setEndangle(BigDecimal endangle) {
        this.endangle = endangle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.INRFIDDEVICEID
     *
     * @return the value of COALFIELDZONE.INRFIDDEVICEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public BigDecimal getInrfiddeviceid() {
        return inrfiddeviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.INRFIDDEVICEID
     *
     * @param inrfiddeviceid the value for COALFIELDZONE.INRFIDDEVICEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setInrfiddeviceid(BigDecimal inrfiddeviceid) {
        this.inrfiddeviceid = inrfiddeviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.OUTRFIDDEVICEID
     *
     * @return the value of COALFIELDZONE.OUTRFIDDEVICEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public BigDecimal getOutrfiddeviceid() {
        return outrfiddeviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.OUTRFIDDEVICEID
     *
     * @param outrfiddeviceid the value for COALFIELDZONE.OUTRFIDDEVICEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setOutrfiddeviceid(BigDecimal outrfiddeviceid) {
        this.outrfiddeviceid = outrfiddeviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.VOICEDEVICEID
     *
     * @return the value of COALFIELDZONE.VOICEDEVICEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public BigDecimal getVoicedeviceid() {
        return voicedeviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.VOICEDEVICEID
     *
     * @param voicedeviceid the value for COALFIELDZONE.VOICEDEVICEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setVoicedeviceid(BigDecimal voicedeviceid) {
        this.voicedeviceid = voicedeviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.QNETARUPPERLIMIT
     *
     * @return the value of COALFIELDZONE.QNETARUPPERLIMIT
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public BigDecimal getQnetarupperlimit() {
        return qnetarupperlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.QNETARUPPERLIMIT
     *
     * @param qnetarupperlimit the value for COALFIELDZONE.QNETARUPPERLIMIT
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setQnetarupperlimit(BigDecimal qnetarupperlimit) {
        this.qnetarupperlimit = qnetarupperlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.QNETARLOWERLIMIT
     *
     * @return the value of COALFIELDZONE.QNETARLOWERLIMIT
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public BigDecimal getQnetarlowerlimit() {
        return qnetarlowerlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.QNETARLOWERLIMIT
     *
     * @param qnetarlowerlimit the value for COALFIELDZONE.QNETARLOWERLIMIT
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setQnetarlowerlimit(BigDecimal qnetarlowerlimit) {
        this.qnetarlowerlimit = qnetarlowerlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.STDUPPERLIMIT
     *
     * @return the value of COALFIELDZONE.STDUPPERLIMIT
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public BigDecimal getStdupperlimit() {
        return stdupperlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.STDUPPERLIMIT
     *
     * @param stdupperlimit the value for COALFIELDZONE.STDUPPERLIMIT
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setStdupperlimit(BigDecimal stdupperlimit) {
        this.stdupperlimit = stdupperlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.STDLOWERLIMIT
     *
     * @return the value of COALFIELDZONE.STDLOWERLIMIT
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public BigDecimal getStdlowerlimit() {
        return stdlowerlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.STDLOWERLIMIT
     *
     * @param stdlowerlimit the value for COALFIELDZONE.STDLOWERLIMIT
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setStdlowerlimit(BigDecimal stdlowerlimit) {
        this.stdlowerlimit = stdlowerlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELDZONE.COALFIELDZONEGUID
     *
     * @return the value of COALFIELDZONE.COALFIELDZONEGUID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getCoalfieldzoneguid() {
        return coalfieldzoneguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELDZONE.COALFIELDZONEGUID
     *
     * @param coalfieldzoneguid the value for COALFIELDZONE.COALFIELDZONEGUID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setCoalfieldzoneguid(String coalfieldzoneguid) {
        this.coalfieldzoneguid = coalfieldzoneguid == null ? null : coalfieldzoneguid.trim();
    }
}