package model;

public class Coalfieldbean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELD.COALFIELDID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String coalfieldid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELD.FIELDCODE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String fieldcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELD.FIELDNAME
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String fieldname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELD.FIELDTYPE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String fieldtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELD.STOREMAX
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String storemax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELD.STOREMIN
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String storemin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELD.LENGTH
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String length;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELD.WIDTH
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELD.HEIGHT
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELD.LEDDEVICEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String leddeviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELD.RADIUS
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String radius;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELD.EXITSTARTANGLE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String exitstartangle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELD.EXITENDANGLE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String exitendangle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELD.COALFIELDGUID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String coalfieldguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELD.WARMHUMIDITY
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private Double warmhumidity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COALFIELD.WARMTEMPERATURE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private Double warmtemperature;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELD.COALFIELDID
     *
     * @return the value of COALFIELD.COALFIELDID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getCoalfieldid() {
        return coalfieldid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELD.COALFIELDID
     *
     * @param coalfieldid the value for COALFIELD.COALFIELDID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setCoalfieldid(String coalfieldid) {
        this.coalfieldid = coalfieldid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELD.FIELDCODE
     *
     * @return the value of COALFIELD.FIELDCODE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getFieldcode() {
        return fieldcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELD.FIELDCODE
     *
     * @param fieldcode the value for COALFIELD.FIELDCODE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setFieldcode(String fieldcode) {
        this.fieldcode = fieldcode == null ? null : fieldcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELD.FIELDNAME
     *
     * @return the value of COALFIELD.FIELDNAME
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getFieldname() {
        return fieldname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELD.FIELDNAME
     *
     * @param fieldname the value for COALFIELD.FIELDNAME
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setFieldname(String fieldname) {
        this.fieldname = fieldname == null ? null : fieldname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELD.FIELDTYPE
     *
     * @return the value of COALFIELD.FIELDTYPE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getFieldtype() {
        return fieldtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELD.FIELDTYPE
     *
     * @param fieldtype the value for COALFIELD.FIELDTYPE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setFieldtype(String fieldtype) {
        this.fieldtype = fieldtype == null ? null : fieldtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELD.STOREMAX
     *
     * @return the value of COALFIELD.STOREMAX
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getStoremax() {
        return storemax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELD.STOREMAX
     *
     * @param storemax the value for COALFIELD.STOREMAX
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setStoremax(String storemax) {
        this.storemax = storemax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELD.STOREMIN
     *
     * @return the value of COALFIELD.STOREMIN
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getStoremin() {
        return storemin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELD.STOREMIN
     *
     * @param storemin the value for COALFIELD.STOREMIN
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setStoremin(String storemin) {
        this.storemin = storemin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELD.LENGTH
     *
     * @return the value of COALFIELD.LENGTH
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELD.LENGTH
     *
     * @param length the value for COALFIELD.LENGTH
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setLength(String length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELD.WIDTH
     *
     * @return the value of COALFIELD.WIDTH
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELD.WIDTH
     *
     * @param width the value for COALFIELD.WIDTH
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setWidth(String width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELD.HEIGHT
     *
     * @return the value of COALFIELD.HEIGHT
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELD.HEIGHT
     *
     * @param height the value for COALFIELD.HEIGHT
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setHeight(String height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELD.LEDDEVICEID
     *
     * @return the value of COALFIELD.LEDDEVICEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getLeddeviceid() {
        return leddeviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELD.LEDDEVICEID
     *
     * @param leddeviceid the value for COALFIELD.LEDDEVICEID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setLeddeviceid(String leddeviceid) {
        this.leddeviceid = leddeviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELD.RADIUS
     *
     * @return the value of COALFIELD.RADIUS
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getRadius() {
        return radius;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELD.RADIUS
     *
     * @param radius the value for COALFIELD.RADIUS
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setRadius(String radius) {
        this.radius = radius;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELD.EXITSTARTANGLE
     *
     * @return the value of COALFIELD.EXITSTARTANGLE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getExitstartangle() {
        return exitstartangle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELD.EXITSTARTANGLE
     *
     * @param exitstartangle the value for COALFIELD.EXITSTARTANGLE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setExitstartangle(String exitstartangle) {
        this.exitstartangle = exitstartangle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELD.EXITENDANGLE
     *
     * @return the value of COALFIELD.EXITENDANGLE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getExitendangle() {
        return exitendangle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELD.EXITENDANGLE
     *
     * @param exitendangle the value for COALFIELD.EXITENDANGLE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setExitendangle(String exitendangle) {
        this.exitendangle = exitendangle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELD.COALFIELDGUID
     *
     * @return the value of COALFIELD.COALFIELDGUID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getCoalfieldguid() {
        return coalfieldguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELD.COALFIELDGUID
     *
     * @param coalfieldguid the value for COALFIELD.COALFIELDGUID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setCoalfieldguid(String coalfieldguid) {
        this.coalfieldguid = coalfieldguid == null ? null : coalfieldguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELD.WARMHUMIDITY
     *
     * @return the value of COALFIELD.WARMHUMIDITY
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public Double getWarmhumidity() {
        return warmhumidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELD.WARMHUMIDITY
     *
     * @param warmhumidity the value for COALFIELD.WARMHUMIDITY
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setWarmhumidity(Double warmhumidity) {
        this.warmhumidity = warmhumidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COALFIELD.WARMTEMPERATURE
     *
     * @return the value of COALFIELD.WARMTEMPERATURE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public Double getWarmtemperature() {
        return warmtemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COALFIELD.WARMTEMPERATURE
     *
     * @param warmtemperature the value for COALFIELD.WARMTEMPERATURE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setWarmtemperature(Double warmtemperature) {
        this.warmtemperature = warmtemperature;
    }
}