package model;

import java.io.File;
import java.math.BigDecimal;
import java.util.Date;

public class Coalbytruckbean {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.COALBYTRUCKID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private BigDecimal coalbytruckid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.LISTNO
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private Object listno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.RFIDNO
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private Object rfidno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.VEHICLENO
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private Object vehicleno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.COALMINEID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private BigDecimal coalmineid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.GROSSSCALEID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private BigDecimal grossscaleid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.TARESCALEID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private BigDecimal tarescaleid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.COALFIELDID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private BigDecimal coalfieldid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.SAMPLECODEMASTERID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private BigDecimal samplecodemasterid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.TRANSPORTID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private BigDecimal transportid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.COALQUALITYID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private BigDecimal coalqualityid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.SAMPLEID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private BigDecimal sampleid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.LISTDATE
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private Date listdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.BILLDATE
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private Date billdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.SAMPLEDATE
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private Date sampledate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.GROSSWEIGHTTIME
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private Date grossweighttime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.CHECKDATE
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private Date checkdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.TARETIME
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private Date taretime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.OUTDATE
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private Date outdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.STATE
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private String state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.SAMPLEAMOUNT
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private BigDecimal sampleamount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.SAMPLEPLACE
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private Object sampleplace;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.JARNO
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private String jarno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.SAMPLEUSER
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private String sampleuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.CHECKUSER
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private String checkuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.LOADWEIGHT
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private BigDecimal loadweight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.TRANSITBILL
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private String transitbill;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.SAMPLETYPE
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private String sampletype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.FREQUENCY
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private String frequency;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.GROSSWEIGHT
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private BigDecimal grossweight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.TARE
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private BigDecimal tare;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.WASTEROCKDISCOUNT
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private BigDecimal wasterockdiscount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.WATERDISCOUNT
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private BigDecimal waterdiscount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.IMPURITYDISCOUNT
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private BigDecimal impuritydiscount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.SAMPLEPHOTO
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private String samplephoto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.REMARK
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.ILLEGAID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private BigDecimal illegaid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.TICKET
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private BigDecimal ticket;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.PUNISHFLAG
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private String punishflag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.TAREDIFF
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private BigDecimal tarediff;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.GROSSWEIGHTDIFF
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private BigDecimal grossweightdiff;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.CHECKPHOTO1
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private Object checkphoto1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.CHECKPHOTO2
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private Object checkphoto2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.CHECKPHOTO3
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private Object checkphoto3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.CHECKPHOTO4
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private Object checkphoto4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.CANCELREASON
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private Object cancelreason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.REALCOALFIELDID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private BigDecimal realcoalfieldid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.CHECKBILLUSER
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private Object checkbilluser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.PRINTBILLUSER
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private Object printbilluser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.SEQUENCE
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private BigDecimal sequence;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.GROSSWEIGHTPHOTO
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private Object grossweightphoto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.TAREPHOTO
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private Object tarephoto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.DEDUCTWEIGHT
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private BigDecimal deductweight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.DEPTH
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private BigDecimal depth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.BUNKERID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private BigDecimal bunkerid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.DATATYPE
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private String datatype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.INCOALFIELDZONEID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private BigDecimal incoalfieldzoneid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.OUTCOALFIELDZONEID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private BigDecimal outcoalfieldzoneid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.QNETAR
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private BigDecimal qnetar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.MT
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private BigDecimal mt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.AD
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private BigDecimal ad;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.R
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private BigDecimal r;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column COALBYTRUCK.COALBYTRUCKGUID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	private String coalbytruckguid;
	
	private File fileimage;

	public File getFileimage() {
		return fileimage;
	}

	public void setFileimage(File fileimage) {
		this.fileimage = fileimage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.COALBYTRUCKID
	 * @return  the value of COALBYTRUCK.COALBYTRUCKID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public BigDecimal getCoalbytruckid() {
		return coalbytruckid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.COALBYTRUCKID
	 * @param coalbytruckid  the value for COALBYTRUCK.COALBYTRUCKID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setCoalbytruckid(BigDecimal coalbytruckid) {
		this.coalbytruckid = coalbytruckid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.LISTNO
	 * @return  the value of COALBYTRUCK.LISTNO
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public Object getListno() {
		return listno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.LISTNO
	 * @param listno  the value for COALBYTRUCK.LISTNO
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setListno(Object listno) {
		this.listno = listno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.RFIDNO
	 * @return  the value of COALBYTRUCK.RFIDNO
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public Object getRfidno() {
		return rfidno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.RFIDNO
	 * @param rfidno  the value for COALBYTRUCK.RFIDNO
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setRfidno(Object rfidno) {
		this.rfidno = rfidno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.VEHICLENO
	 * @return  the value of COALBYTRUCK.VEHICLENO
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public Object getVehicleno() {
		return vehicleno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.VEHICLENO
	 * @param vehicleno  the value for COALBYTRUCK.VEHICLENO
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setVehicleno(Object vehicleno) {
		this.vehicleno = vehicleno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.COALMINEID
	 * @return  the value of COALBYTRUCK.COALMINEID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public BigDecimal getCoalmineid() {
		return coalmineid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.COALMINEID
	 * @param coalmineid  the value for COALBYTRUCK.COALMINEID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setCoalmineid(BigDecimal coalmineid) {
		this.coalmineid = coalmineid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.GROSSSCALEID
	 * @return  the value of COALBYTRUCK.GROSSSCALEID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public BigDecimal getGrossscaleid() {
		return grossscaleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.GROSSSCALEID
	 * @param grossscaleid  the value for COALBYTRUCK.GROSSSCALEID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setGrossscaleid(BigDecimal grossscaleid) {
		this.grossscaleid = grossscaleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.TARESCALEID
	 * @return  the value of COALBYTRUCK.TARESCALEID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public BigDecimal getTarescaleid() {
		return tarescaleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.TARESCALEID
	 * @param tarescaleid  the value for COALBYTRUCK.TARESCALEID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setTarescaleid(BigDecimal tarescaleid) {
		this.tarescaleid = tarescaleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.COALFIELDID
	 * @return  the value of COALBYTRUCK.COALFIELDID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public BigDecimal getCoalfieldid() {
		return coalfieldid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.COALFIELDID
	 * @param coalfieldid  the value for COALBYTRUCK.COALFIELDID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setCoalfieldid(BigDecimal coalfieldid) {
		this.coalfieldid = coalfieldid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.SAMPLECODEMASTERID
	 * @return  the value of COALBYTRUCK.SAMPLECODEMASTERID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public BigDecimal getSamplecodemasterid() {
		return samplecodemasterid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.SAMPLECODEMASTERID
	 * @param samplecodemasterid  the value for COALBYTRUCK.SAMPLECODEMASTERID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setSamplecodemasterid(BigDecimal samplecodemasterid) {
		this.samplecodemasterid = samplecodemasterid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.TRANSPORTID
	 * @return  the value of COALBYTRUCK.TRANSPORTID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public BigDecimal getTransportid() {
		return transportid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.TRANSPORTID
	 * @param transportid  the value for COALBYTRUCK.TRANSPORTID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setTransportid(BigDecimal transportid) {
		this.transportid = transportid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.COALQUALITYID
	 * @return  the value of COALBYTRUCK.COALQUALITYID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public BigDecimal getCoalqualityid() {
		return coalqualityid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.COALQUALITYID
	 * @param coalqualityid  the value for COALBYTRUCK.COALQUALITYID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setCoalqualityid(BigDecimal coalqualityid) {
		this.coalqualityid = coalqualityid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.SAMPLEID
	 * @return  the value of COALBYTRUCK.SAMPLEID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public BigDecimal getSampleid() {
		return sampleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.SAMPLEID
	 * @param sampleid  the value for COALBYTRUCK.SAMPLEID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setSampleid(BigDecimal sampleid) {
		this.sampleid = sampleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.LISTDATE
	 * @return  the value of COALBYTRUCK.LISTDATE
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public Date getListdate() {
		return listdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.LISTDATE
	 * @param listdate  the value for COALBYTRUCK.LISTDATE
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setListdate(Date listdate) {
		this.listdate = listdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.BILLDATE
	 * @return  the value of COALBYTRUCK.BILLDATE
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public Date getBilldate() {
		return billdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.BILLDATE
	 * @param billdate  the value for COALBYTRUCK.BILLDATE
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setBilldate(Date billdate) {
		this.billdate = billdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.SAMPLEDATE
	 * @return  the value of COALBYTRUCK.SAMPLEDATE
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public Date getSampledate() {
		return sampledate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.SAMPLEDATE
	 * @param sampledate  the value for COALBYTRUCK.SAMPLEDATE
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setSampledate(Date sampledate) {
		this.sampledate = sampledate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.GROSSWEIGHTTIME
	 * @return  the value of COALBYTRUCK.GROSSWEIGHTTIME
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public Date getGrossweighttime() {
		return grossweighttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.GROSSWEIGHTTIME
	 * @param grossweighttime  the value for COALBYTRUCK.GROSSWEIGHTTIME
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setGrossweighttime(Date grossweighttime) {
		this.grossweighttime = grossweighttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.CHECKDATE
	 * @return  the value of COALBYTRUCK.CHECKDATE
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public Date getCheckdate() {
		return checkdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.CHECKDATE
	 * @param checkdate  the value for COALBYTRUCK.CHECKDATE
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setCheckdate(Date checkdate) {
		this.checkdate = checkdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.TARETIME
	 * @return  the value of COALBYTRUCK.TARETIME
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public Date getTaretime() {
		return taretime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.TARETIME
	 * @param taretime  the value for COALBYTRUCK.TARETIME
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setTaretime(Date taretime) {
		this.taretime = taretime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.OUTDATE
	 * @return  the value of COALBYTRUCK.OUTDATE
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public Date getOutdate() {
		return outdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.OUTDATE
	 * @param outdate  the value for COALBYTRUCK.OUTDATE
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setOutdate(Date outdate) {
		this.outdate = outdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.STATE
	 * @return  the value of COALBYTRUCK.STATE
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.STATE
	 * @param state  the value for COALBYTRUCK.STATE
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setState(String state) {
		this.state = state == null ? null : state.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.SAMPLEAMOUNT
	 * @return  the value of COALBYTRUCK.SAMPLEAMOUNT
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public BigDecimal getSampleamount() {
		return sampleamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.SAMPLEAMOUNT
	 * @param sampleamount  the value for COALBYTRUCK.SAMPLEAMOUNT
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setSampleamount(BigDecimal sampleamount) {
		this.sampleamount = sampleamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.SAMPLEPLACE
	 * @return  the value of COALBYTRUCK.SAMPLEPLACE
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public Object getSampleplace() {
		return sampleplace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.SAMPLEPLACE
	 * @param sampleplace  the value for COALBYTRUCK.SAMPLEPLACE
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setSampleplace(Object sampleplace) {
		this.sampleplace = sampleplace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.JARNO
	 * @return  the value of COALBYTRUCK.JARNO
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public String getJarno() {
		return jarno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.JARNO
	 * @param jarno  the value for COALBYTRUCK.JARNO
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setJarno(String jarno) {
		this.jarno = jarno == null ? null : jarno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.SAMPLEUSER
	 * @return  the value of COALBYTRUCK.SAMPLEUSER
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public String getSampleuser() {
		return sampleuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.SAMPLEUSER
	 * @param sampleuser  the value for COALBYTRUCK.SAMPLEUSER
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setSampleuser(String sampleuser) {
		this.sampleuser = sampleuser == null ? null : sampleuser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.CHECKUSER
	 * @return  the value of COALBYTRUCK.CHECKUSER
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public String getCheckuser() {
		return checkuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.CHECKUSER
	 * @param checkuser  the value for COALBYTRUCK.CHECKUSER
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setCheckuser(String checkuser) {
		this.checkuser = checkuser == null ? null : checkuser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.LOADWEIGHT
	 * @return  the value of COALBYTRUCK.LOADWEIGHT
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public BigDecimal getLoadweight() {
		return loadweight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.LOADWEIGHT
	 * @param loadweight  the value for COALBYTRUCK.LOADWEIGHT
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setLoadweight(BigDecimal loadweight) {
		this.loadweight = loadweight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.TRANSITBILL
	 * @return  the value of COALBYTRUCK.TRANSITBILL
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public String getTransitbill() {
		return transitbill;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.TRANSITBILL
	 * @param transitbill  the value for COALBYTRUCK.TRANSITBILL
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setTransitbill(String transitbill) {
		this.transitbill = transitbill == null ? null : transitbill.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.SAMPLETYPE
	 * @return  the value of COALBYTRUCK.SAMPLETYPE
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public String getSampletype() {
		return sampletype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.SAMPLETYPE
	 * @param sampletype  the value for COALBYTRUCK.SAMPLETYPE
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setSampletype(String sampletype) {
		this.sampletype = sampletype == null ? null : sampletype.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.FREQUENCY
	 * @return  the value of COALBYTRUCK.FREQUENCY
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public String getFrequency() {
		return frequency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.FREQUENCY
	 * @param frequency  the value for COALBYTRUCK.FREQUENCY
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setFrequency(String frequency) {
		this.frequency = frequency == null ? null : frequency.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.GROSSWEIGHT
	 * @return  the value of COALBYTRUCK.GROSSWEIGHT
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public BigDecimal getGrossweight() {
		return grossweight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.GROSSWEIGHT
	 * @param grossweight  the value for COALBYTRUCK.GROSSWEIGHT
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setGrossweight(BigDecimal grossweight) {
		this.grossweight = grossweight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.TARE
	 * @return  the value of COALBYTRUCK.TARE
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public BigDecimal getTare() {
		return tare;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.TARE
	 * @param tare  the value for COALBYTRUCK.TARE
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setTare(BigDecimal tare) {
		this.tare = tare;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.WASTEROCKDISCOUNT
	 * @return  the value of COALBYTRUCK.WASTEROCKDISCOUNT
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public BigDecimal getWasterockdiscount() {
		return wasterockdiscount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.WASTEROCKDISCOUNT
	 * @param wasterockdiscount  the value for COALBYTRUCK.WASTEROCKDISCOUNT
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setWasterockdiscount(BigDecimal wasterockdiscount) {
		this.wasterockdiscount = wasterockdiscount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.WATERDISCOUNT
	 * @return  the value of COALBYTRUCK.WATERDISCOUNT
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public BigDecimal getWaterdiscount() {
		return waterdiscount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.WATERDISCOUNT
	 * @param waterdiscount  the value for COALBYTRUCK.WATERDISCOUNT
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setWaterdiscount(BigDecimal waterdiscount) {
		this.waterdiscount = waterdiscount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.IMPURITYDISCOUNT
	 * @return  the value of COALBYTRUCK.IMPURITYDISCOUNT
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public BigDecimal getImpuritydiscount() {
		return impuritydiscount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.IMPURITYDISCOUNT
	 * @param impuritydiscount  the value for COALBYTRUCK.IMPURITYDISCOUNT
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setImpuritydiscount(BigDecimal impuritydiscount) {
		this.impuritydiscount = impuritydiscount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.SAMPLEPHOTO
	 * @return  the value of COALBYTRUCK.SAMPLEPHOTO
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public String getSamplephoto() {
		return samplephoto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.SAMPLEPHOTO
	 * @param samplephoto  the value for COALBYTRUCK.SAMPLEPHOTO
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setSamplephoto(String samplephoto) {
		this.samplephoto = samplephoto == null ? null : samplephoto.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.REMARK
	 * @return  the value of COALBYTRUCK.REMARK
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.REMARK
	 * @param remark  the value for COALBYTRUCK.REMARK
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.ILLEGAID
	 * @return  the value of COALBYTRUCK.ILLEGAID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public BigDecimal getIllegaid() {
		return illegaid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.ILLEGAID
	 * @param illegaid  the value for COALBYTRUCK.ILLEGAID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setIllegaid(BigDecimal illegaid) {
		this.illegaid = illegaid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.TICKET
	 * @return  the value of COALBYTRUCK.TICKET
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public BigDecimal getTicket() {
		return ticket;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.TICKET
	 * @param ticket  the value for COALBYTRUCK.TICKET
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setTicket(BigDecimal ticket) {
		this.ticket = ticket;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.PUNISHFLAG
	 * @return  the value of COALBYTRUCK.PUNISHFLAG
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public String getPunishflag() {
		return punishflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.PUNISHFLAG
	 * @param punishflag  the value for COALBYTRUCK.PUNISHFLAG
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setPunishflag(String punishflag) {
		this.punishflag = punishflag == null ? null : punishflag.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.TAREDIFF
	 * @return  the value of COALBYTRUCK.TAREDIFF
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public BigDecimal getTarediff() {
		return tarediff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.TAREDIFF
	 * @param tarediff  the value for COALBYTRUCK.TAREDIFF
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setTarediff(BigDecimal tarediff) {
		this.tarediff = tarediff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.GROSSWEIGHTDIFF
	 * @return  the value of COALBYTRUCK.GROSSWEIGHTDIFF
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public BigDecimal getGrossweightdiff() {
		return grossweightdiff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.GROSSWEIGHTDIFF
	 * @param grossweightdiff  the value for COALBYTRUCK.GROSSWEIGHTDIFF
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setGrossweightdiff(BigDecimal grossweightdiff) {
		this.grossweightdiff = grossweightdiff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.CHECKPHOTO1
	 * @return  the value of COALBYTRUCK.CHECKPHOTO1
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public Object getCheckphoto1() {
		return checkphoto1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.CHECKPHOTO1
	 * @param checkphoto1  the value for COALBYTRUCK.CHECKPHOTO1
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setCheckphoto1(Object checkphoto1) {
		this.checkphoto1 = checkphoto1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.CHECKPHOTO2
	 * @return  the value of COALBYTRUCK.CHECKPHOTO2
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public Object getCheckphoto2() {
		return checkphoto2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.CHECKPHOTO2
	 * @param checkphoto2  the value for COALBYTRUCK.CHECKPHOTO2
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setCheckphoto2(Object checkphoto2) {
		this.checkphoto2 = checkphoto2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.CHECKPHOTO3
	 * @return  the value of COALBYTRUCK.CHECKPHOTO3
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public Object getCheckphoto3() {
		return checkphoto3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.CHECKPHOTO3
	 * @param checkphoto3  the value for COALBYTRUCK.CHECKPHOTO3
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setCheckphoto3(Object checkphoto3) {
		this.checkphoto3 = checkphoto3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.CHECKPHOTO4
	 * @return  the value of COALBYTRUCK.CHECKPHOTO4
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public Object getCheckphoto4() {
		return checkphoto4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.CHECKPHOTO4
	 * @param checkphoto4  the value for COALBYTRUCK.CHECKPHOTO4
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setCheckphoto4(Object checkphoto4) {
		this.checkphoto4 = checkphoto4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.CANCELREASON
	 * @return  the value of COALBYTRUCK.CANCELREASON
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public Object getCancelreason() {
		return cancelreason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.CANCELREASON
	 * @param cancelreason  the value for COALBYTRUCK.CANCELREASON
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setCancelreason(Object cancelreason) {
		this.cancelreason = cancelreason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.REALCOALFIELDID
	 * @return  the value of COALBYTRUCK.REALCOALFIELDID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public BigDecimal getRealcoalfieldid() {
		return realcoalfieldid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.REALCOALFIELDID
	 * @param realcoalfieldid  the value for COALBYTRUCK.REALCOALFIELDID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setRealcoalfieldid(BigDecimal realcoalfieldid) {
		this.realcoalfieldid = realcoalfieldid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.CHECKBILLUSER
	 * @return  the value of COALBYTRUCK.CHECKBILLUSER
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public Object getCheckbilluser() {
		return checkbilluser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.CHECKBILLUSER
	 * @param checkbilluser  the value for COALBYTRUCK.CHECKBILLUSER
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setCheckbilluser(Object checkbilluser) {
		this.checkbilluser = checkbilluser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.PRINTBILLUSER
	 * @return  the value of COALBYTRUCK.PRINTBILLUSER
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public Object getPrintbilluser() {
		return printbilluser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.PRINTBILLUSER
	 * @param printbilluser  the value for COALBYTRUCK.PRINTBILLUSER
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setPrintbilluser(Object printbilluser) {
		this.printbilluser = printbilluser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.SEQUENCE
	 * @return  the value of COALBYTRUCK.SEQUENCE
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public BigDecimal getSequence() {
		return sequence;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.SEQUENCE
	 * @param sequence  the value for COALBYTRUCK.SEQUENCE
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setSequence(BigDecimal sequence) {
		this.sequence = sequence;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.GROSSWEIGHTPHOTO
	 * @return  the value of COALBYTRUCK.GROSSWEIGHTPHOTO
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public Object getGrossweightphoto() {
		return grossweightphoto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.GROSSWEIGHTPHOTO
	 * @param grossweightphoto  the value for COALBYTRUCK.GROSSWEIGHTPHOTO
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setGrossweightphoto(Object grossweightphoto) {
		this.grossweightphoto = grossweightphoto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.TAREPHOTO
	 * @return  the value of COALBYTRUCK.TAREPHOTO
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public Object getTarephoto() {
		return tarephoto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.TAREPHOTO
	 * @param tarephoto  the value for COALBYTRUCK.TAREPHOTO
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setTarephoto(Object tarephoto) {
		this.tarephoto = tarephoto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.DEDUCTWEIGHT
	 * @return  the value of COALBYTRUCK.DEDUCTWEIGHT
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public BigDecimal getDeductweight() {
		return deductweight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.DEDUCTWEIGHT
	 * @param deductweight  the value for COALBYTRUCK.DEDUCTWEIGHT
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setDeductweight(BigDecimal deductweight) {
		this.deductweight = deductweight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.DEPTH
	 * @return  the value of COALBYTRUCK.DEPTH
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public BigDecimal getDepth() {
		return depth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.DEPTH
	 * @param depth  the value for COALBYTRUCK.DEPTH
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setDepth(BigDecimal depth) {
		this.depth = depth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.BUNKERID
	 * @return  the value of COALBYTRUCK.BUNKERID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public BigDecimal getBunkerid() {
		return bunkerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.BUNKERID
	 * @param bunkerid  the value for COALBYTRUCK.BUNKERID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setBunkerid(BigDecimal bunkerid) {
		this.bunkerid = bunkerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.DATATYPE
	 * @return  the value of COALBYTRUCK.DATATYPE
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public String getDatatype() {
		return datatype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.DATATYPE
	 * @param datatype  the value for COALBYTRUCK.DATATYPE
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setDatatype(String datatype) {
		this.datatype = datatype == null ? null : datatype.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.INCOALFIELDZONEID
	 * @return  the value of COALBYTRUCK.INCOALFIELDZONEID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public BigDecimal getIncoalfieldzoneid() {
		return incoalfieldzoneid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.INCOALFIELDZONEID
	 * @param incoalfieldzoneid  the value for COALBYTRUCK.INCOALFIELDZONEID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setIncoalfieldzoneid(BigDecimal incoalfieldzoneid) {
		this.incoalfieldzoneid = incoalfieldzoneid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.OUTCOALFIELDZONEID
	 * @return  the value of COALBYTRUCK.OUTCOALFIELDZONEID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public BigDecimal getOutcoalfieldzoneid() {
		return outcoalfieldzoneid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.OUTCOALFIELDZONEID
	 * @param outcoalfieldzoneid  the value for COALBYTRUCK.OUTCOALFIELDZONEID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setOutcoalfieldzoneid(BigDecimal outcoalfieldzoneid) {
		this.outcoalfieldzoneid = outcoalfieldzoneid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.QNETAR
	 * @return  the value of COALBYTRUCK.QNETAR
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public BigDecimal getQnetar() {
		return qnetar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.QNETAR
	 * @param qnetar  the value for COALBYTRUCK.QNETAR
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setQnetar(BigDecimal qnetar) {
		this.qnetar = qnetar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.MT
	 * @return  the value of COALBYTRUCK.MT
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public BigDecimal getMt() {
		return mt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.MT
	 * @param mt  the value for COALBYTRUCK.MT
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setMt(BigDecimal mt) {
		this.mt = mt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.AD
	 * @return  the value of COALBYTRUCK.AD
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public BigDecimal getAd() {
		return ad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.AD
	 * @param ad  the value for COALBYTRUCK.AD
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setAd(BigDecimal ad) {
		this.ad = ad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.R
	 * @return  the value of COALBYTRUCK.R
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public BigDecimal getR() {
		return r;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.R
	 * @param r  the value for COALBYTRUCK.R
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setR(BigDecimal r) {
		this.r = r;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column COALBYTRUCK.COALBYTRUCKGUID
	 * @return  the value of COALBYTRUCK.COALBYTRUCKGUID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public String getCoalbytruckguid() {
		return coalbytruckguid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column COALBYTRUCK.COALBYTRUCKGUID
	 * @param coalbytruckguid  the value for COALBYTRUCK.COALBYTRUCKGUID
	 * @mbggenerated  Tue Aug 29 15:07:01 CST 2017
	 */
	public void setCoalbytruckguid(String coalbytruckguid) {
		this.coalbytruckguid = coalbytruckguid == null ? null : coalbytruckguid.trim();
	}
}