package model;

public class Userinfobean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.USERID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.USERNAME
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.LOGINNAME
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String loginname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.LOGINPWD
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String loginpwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.CREATETIME
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.CREATEUSERID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String createuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.STATE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.ACCESSCONTROLNO
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String accesscontrolno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.PHOTO
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.PHONENUMBER
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    private String phonenumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.USERID
     *
     * @return the value of USERINFO.USERID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.USERID
     *
     * @param userid the value for USERINFO.USERID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.USERNAME
     *
     * @return the value of USERINFO.USERNAME
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.USERNAME
     *
     * @param username the value for USERINFO.USERNAME
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.LOGINNAME
     *
     * @return the value of USERINFO.LOGINNAME
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.LOGINNAME
     *
     * @param loginname the value for USERINFO.LOGINNAME
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname == null ? null : loginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.LOGINPWD
     *
     * @return the value of USERINFO.LOGINPWD
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getLoginpwd() {
        return loginpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.LOGINPWD
     *
     * @param loginpwd the value for USERINFO.LOGINPWD
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setLoginpwd(String loginpwd) {
        this.loginpwd = loginpwd == null ? null : loginpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.CREATETIME
     *
     * @return the value of USERINFO.CREATETIME
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.CREATETIME
     *
     * @param createtime the value for USERINFO.CREATETIME
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.CREATEUSERID
     *
     * @return the value of USERINFO.CREATEUSERID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.CREATEUSERID
     *
     * @param createuserid the value for USERINFO.CREATEUSERID
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid == null ? null : createuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.STATE
     *
     * @return the value of USERINFO.STATE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.STATE
     *
     * @param state the value for USERINFO.STATE
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.ACCESSCONTROLNO
     *
     * @return the value of USERINFO.ACCESSCONTROLNO
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getAccesscontrolno() {
        return accesscontrolno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.ACCESSCONTROLNO
     *
     * @param accesscontrolno the value for USERINFO.ACCESSCONTROLNO
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setAccesscontrolno(String accesscontrolno) {
        this.accesscontrolno = accesscontrolno == null ? null : accesscontrolno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.PHOTO
     *
     * @return the value of USERINFO.PHOTO
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.PHOTO
     *
     * @param photo the value for USERINFO.PHOTO
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.PHONENUMBER
     *
     * @return the value of USERINFO.PHONENUMBER
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public String getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.PHONENUMBER
     *
     * @param phonenumber the value for USERINFO.PHONENUMBER
     *
     * @mbggenerated Tue Aug 29 15:14:39 CST 2017
     */
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber == null ? null : phonenumber.trim();
    }
}